from django.conf import settings

field_map_as_316 = {
    "fields": [
        "article_no",
        "description",
        "article_group_no",
        "abc_license_plate",
        "manufacturer",
        "manufacturer_article_no",
        "packaging_unit",
        "alternative_article_no",
        "customs_position",
        "country_of_origin",
        "blocked",
        "country_of_origin_alt",
        "vat_rate",
        "created_on",
        "medical_device",
        "drug",
        "pzn_no",
        "avg_delivery_time",
        "order_suggestion",
        "un_number",
        "packing_unit",
        "hazard_code",
        "package_contents",
        "length",
        "width",
        "height",
        "weight",
        "dangerous_goods",
        "store_refrigerated",
        "batch_number_required",
        "serial_number_required",
        "mhd_compulsory",
        "warehouse",
        "product_group_no",
        "freely_available",
        "hibc_manufacturer_id",
        "hibc_article_no",
        "hibc_packaging_index",
    ],
    "boolean_fields": [
        "blocked",
        "order_suggestion",
        "dangerous_goods",
        "store_refrigerated",
        "batch_number_required",
        "serial_number_required",
        "mhd_compulsory",
        "freely_available",
    ],
    "date_fields": ["created_on"],
    "code_fields": [],
    "model_label": "gls.GLSMasterData",
    "unique_field": "article_no",
}

field_map_lb_315 = {
    "fields": [
        "article_no",
        "inventory",
        "ordered_qty",
        "next_receipt_date",
        "next_receipt_qty",
    ],
    "boolean_fields": [],
    "date_fields": ["next_receipt_date"],
    "code_fields": [],
    "model_label": "gls.GLSStockLevel",
    "unique_field": "article_no",
}

field_map_pl_317 = {
    "fields": [
        "article_no",
        "purchase_price",
        "bill_back_price",
        "recommended_retail_price",
    ],
    "boolean_fields": [],
    "date_fields": [],
    "code_fields": [],
    "model_label": "gls.GLSPriceList",
    "unique_field": "article_no",
}

field_map_ls_320 = {
    "fields": [
        "supplier_no",
        "name1",
        "name2",
        "street",
        "country",
        "postal_code",
        "city",
        "search_term",
        "phone",
        "fax",
        "email",
        "vat_id",
        "url",
        "blocked",
        "drug_ban",
        "packaging_reg_no",
    ],
    "boolean_fields": ["blocked", "drug_ban"],
    "date_fields": [],
    "code_fields": [],
    "model_label": "gls.GLSSupplier",
    "unique_field": "supplier_no",
}

field_map_no_304 = {
    "fields": [
        "record_type",
        "order_number",
        "position",
        "actual_value",
        "control_number",
        "shipping_info",
        "packing_time",
        "goods_receipt_date",
        "ordered_qty",
        "info",
        "order_method",
        "end_customer_id",
        "customer_number",
        "article_no",
        "unit_price",
        "internal_user",
        "document_number",
        "delivery_note_date",
        "expected_delivery_date",
        "backorder_text",
    ],
    "boolean_fields": [],
    "date_fields": [
        "goods_receipt_date",
        "delivery_note_date",
        "expected_delivery_date",
    ],
    "code_fields": [],
    "model_label": "gls.GLSOrderConfirmation",
    "unique_field": None,
}

field_map_x_310 = {
    "fields": [
        "order_number",
        "position_number",
        "backorder_qty",
        "next_goods_receipt",
        "order_receipt_date",
        "confirmed_delivery_date",
        "customer_number",
        "article_no",
        "description",
    ],
    "boolean_fields": [],
    "date_fields": [
        "next_goods_receipt",
        "order_receipt_date",
        "confirmed_delivery_date",
    ],
    "code_fields": [],
    "model_label": "gls.GLSBackorder",
    "unique_field": None,
}


field_map_501 = {
    "fields": [
        "action_code",
        "origin_code",
        "valid_from",
        "valid_to",
        "customer_number",
        "short_text",
        "action_type",
        "min_value_eur",
        "max_value_eur",
        "min_qty",
        "max_qty",
        "invoice_text_1",
        "set_price",
        "currency",
        "bom_flag",
        "print_invoice_text",
        "natural_discount_qty",
        "credit_flag",
    ],
    "boolean_fields": ["print_invoice_text", "credit_flag"],
    "date_fields": ["valid_from", "valid_to"],
    "code_fields": [],
    "model_label": "gls.GLSPromotionHeader",
    "unique_field": "action_code",
}


field_map_502 = {
    "fields": [
        "action_code",
        "origin_code",
        "position_number",
        "article_no",
        "set_qty",
        "qty_editable",
        "incentive_article",
        "net_gross_flag",
    ],
    "boolean_fields": ["incentive_article"],
    "date_fields": [],
    "code_fields": [],
    "model_label": "gls.GLSPromotionPosition",
    "unique_field": None,
}


field_map_503 = {
    "fields": [
        "action_code",
        "origin_code",
        "article_no",
        "valid_from",
        "valid_to",
        "promotion_price",
        "qty_tier_1",
        "qty_tier_2",
        "qty_tier_3",
        "qty_tier_4",
        "qty_tier_5",
        "price_tier_1",
        "price_tier_2",
        "price_tier_3",
        "price_tier_4",
        "price_tier_5",
        "change_flag",
        "promotional_purchase_price",
        "net_gross_flag",
    ],
    "boolean_fields": [],
    "date_fields": ["valid_from", "valid_to"],
    "code_fields": [],
    "model_label": "gls.GLSPromotionPrice",
    "unique_field": None,
}


field_map_101 = {
    "fields": [
        ("record_type", "1c"),
        ("order_number", "20c"),
        ("branch_no", "20c"),
        ("customer_id", "20c"),
        ("end_customer_no", "10c"),
        ("billing_name", "30t"),
        ("billing_name2", "30t"),
        ("billing_name3", "30t"),
        ("billing_name4", "30t"),
        ("billing_street", "30t"),
        ("billing_zip", "10c"),
        ("billing_city", "30t"),
        ("billing_country", "10c"),
        ("shipping_name", "30t"),
        ("shipping_name2", "30t"),
        ("shipping_name3", "30t"),
        ("shipping_name4", "30t"),
        ("shipping_street", "30t"),
        ("shipping_zip", "10c"),
        ("shipping_city", "30t"),
        ("shipping_country", "10c"),
        ("distribution_key", "3c"),
        ("document_type", "3c"),
        ("copies", "2d"),
        ("open_field", "1c_bool"),
        ("message", "50t"),
        ("carrier_code", "2t"),
        ("registration_code", "20c"),
        ("redelivery_method", "1d"),
        ("order_type", "1d"),
        ("delivery_date", "TT.MM.JJ"),
        ("contact_person", "30t"),
        ("email_address", "50c"),
        ("phone_number", "30c"),
        ("discount_period", "3d"),
        ("currency", "3c"),
        ("show_price_on_ls", "1c_bool"),
        ("print_format", "1c"),
        ("vat_id", "20c"),
        ("export_country", "10c"),
    ],
    "model_label": "gls.GLSOrderHeader",
}


field_map_102 = {
    "fields": [
        ("record_type", "1c"),
        ("order_number", "20c"),
        ("position", "10c"),
        ("gls_article_no", "20c"),
        ("customer_article_no", "20c"),
        ("unit_price", "12d,"),
        ("description", "50t"),
        ("description2", "35t"),
        ("qty", "12d,"),
        ("promotion_code", "10c"),
        ("promotion_origin", "1c"),
        ("free_item", "1c_bool"),
    ],
    "model_label": "gls.GLSOrderLine",
}


DATA_FIELD_MAPS = {
    settings.GLS_FILE_AS316: field_map_as_316,
    settings.GLS_FILE_LB315: field_map_lb_315,
    settings.GLS_FILE_PL317: field_map_pl_317,
    settings.GLS_FILE_LS320: field_map_ls_320,
    settings.GLS_FILE_NO304: field_map_no_304,
    settings.GLS_FILE_X310: field_map_x_310,
    settings.GLS_FILE_501: field_map_501,
    settings.GLS_FILE_502: field_map_502,
    settings.GLS_FILE_503: field_map_503,
    settings.GLS_FILE_101: field_map_101,
    settings.GLS_FILE_102: field_map_102,
}
