# Generated by Django 5.2.7 on 2025-11-14 22:23

import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_article_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_blocked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='file', max_length=100)),
                ('file_type', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel')], default='csv', max_length=10)),
                ('config', models.JSONField(default=dict, editable=False)),
                ('download_url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('net_own', models.DecimalField(decimal_places=2, help_text='Net price from AERA for Jasado’s own offer', max_digits=12, verbose_name='AERA Own Net Price')),
                ('net_top_1', models.DecimalField(decimal_places=2, help_text='Lowest competitor net price on AERA', max_digits=12, verbose_name='AERA Top 1 Net Price')),
                ('net_top_2', models.DecimalField(decimal_places=2, help_text='Second lowest competitor net price on AERA', max_digits=12, verbose_name='AERA Top 2 Net Price')),
                ('net_top_3', models.DecimalField(decimal_places=2, help_text='Third lowest competitor net price on AERA', max_digits=12, verbose_name='AERA Top 3 Net Price')),
                ('calculated_sales_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final sales price calculated by middleware', max_digits=12, null=True, verbose_name='Calculated Price')),
                ('last_calculated', models.DateTimeField(blank=True, help_text='Timestamp of the last price calculation', null=True, verbose_name='Last Calculated')),
                ('last_fetch_from_aera', models.DateTimeField(blank=True, help_text='Timestamp of the last data fetch from AERA', null=True, verbose_name='Last Fetched from AERA')),
                ('product', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dynamic_price', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('article_no', models.CharField(max_length=50, unique=True)),
                ('manufacturer_article_no', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_item', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('article_no', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('width', utils.CleanDecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('height', utils.CleanDecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('length', utils.CleanDecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('weight', utils.CleanDecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('manufacturer_article_no', models.CharField(blank=True, max_length=50, null=True)),
                ('article_calculation_price', utils.CleanDecimalField(blank=True, decimal_places=4, help_text='purchase price already including handling fee', max_digits=14, null=True)),
                ('batch_number_required', models.BooleanField(default=True)),
                ('gtin', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('temperature_stable_shipping', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_master_data', to='core.product')),
            ],
            options={
                'verbose_name': 'Non-GLS Master Data',
                'verbose_name_plural': 'Non-GLS Master Data',
            },
        ),
    ]
