# Generated by Django 5.2.7 on 2025-11-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='article_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blockedproduct',
            unique_together={('manufacturer_article_no', 'manufacturer')},
        ),
    ]
