# Generated by Django 5.2.7 on 2025-11-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_additionalmasterdata_article_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedproduct',
            unique_together=set(),
        ),
    ]
