# Generated by Django 5.2.7 on 2025-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_blockedproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer_article_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
