# Generated by Django 5.2.7 on 2025-11-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_manufacturer_article_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_master_data', to='core.product'),
        ),
        migrations.AlterField(
            model_name='blockedproduct',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_item', to='core.product'),
        ),
    ]
