# Generated by Django 5.2.7 on 2025-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_additionalmasterdata_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalmasterdata',
            name='temperature_stable_shipping',
        ),
        migrations.AddField(
            model_name='additionalmasterdata',
            name='store_refrigerated',
            field=models.BooleanField(default=False),
        ),
    ]
