# Generated by Django 5.2.7 on 2025-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_additionalmasterdata_temperature_stable_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='GLS', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_article_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer_article_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supplier', 'supplier_article_no')},
        ),
    ]
