# Generated by Django 5.2.7 on 2025-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_supplier_product_supplier_article_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
