# Generated by Django 5.2.7 on 2025-11-17 19:10

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_manufacturer_id_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmasterdata',
            name='stock',
            field=utils.CleanDecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_master_data', to='core.product'),
        ),
    ]
