# Generated by Django 5.2.7 on 2025-11-18 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_additionalmasterdata_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalmasterdata',
            options={'verbose_name': 'Non-GLS Product', 'verbose_name_plural': 'Non-GLS Products'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'All Products'},
        ),
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_master_data', to='core.product'),
        ),
    ]
