# Generated by Django 5.2.7 on 2025-11-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_additionalmasterdata_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additionalmasterdata',
            unique_together={('manufacturer_article_no', 'manufacturer')},
        ),
    ]
