# Generated by Django 5.2.7 on 2025-11-26 05:16

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_additionalmasterdata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddlewareSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Global minimum margin')),
                ('competitor_rule', models.CharField(choices=[('cheapest', 'Cheapest offer'), ('average', 'Average of 3 cheapest offers')], default='cheapest', max_length=20, verbose_name='Default competitor rule')),
                ('undercut_value', models.DecimalField(decimal_places=2, default=0, help_text='Amount to subtract from competitor price (x.xx €)', max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'verbose_name': 'Automation Log', 'verbose_name_plural': 'Automation Logs'},
        ),
        migrations.AddField(
            model_name='product',
            name='gls_article_group_no',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last calculated sales price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store_refrigerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='height',
            field=utils.CleanDecimalField(blank=True, decimal_places=4, help_text='unit(mm)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='length',
            field=utils.CleanDecimalField(blank=True, decimal_places=4, help_text='unit(mm)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='weight',
            field=utils.CleanDecimalField(blank=True, decimal_places=4, help_text='weight(g)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='width',
            field=utils.CleanDecimalField(blank=True, decimal_places=4, help_text='unit(mm)', max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Product Price History',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.DeleteModel(
            name='DynamicPrice',
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['product', '-calculated_at'], name='core_produc_product_95a843_idx'),
        ),
        migrations.AddIndex(
            model_name='productpricehistory',
            index=models.Index(fields=['calculated_at'], name='core_produc_calcula_eb2ad6_idx'),
        ),
    ]
