# Generated by Django 5.2.7 on 2025-11-26 05:20

from django.db import migrations
from apps.core.models import MiddlewareSetting


def create_default_middleware_settings(apps, schema_editor):
    if not MiddlewareSetting.objects.exists():
        MiddlewareSetting.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_middlewaresetting_alter_logentry_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_default_middleware_settings, migrations.RunPython.noop
        ),
    ]
