# Generated by Django 5.2.7 on 2025-11-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_create_default_middleware_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gls_article_group_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
