# Generated by Django 5.2.7 on 2025-11-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_gls_article_group_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmasterdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='middlewaresetting',
            name='minimum_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Eg 2.5%, 1.5%', max_digits=5, verbose_name='Global minimum margin in percentage (%)'),
        ),
    ]
