# Generated by Django 5.2.7 on 2025-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_additionalmasterdata_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGtin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gtin', models.CharField(blank=True, max_length=200, null=True, verbose_name='ean')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('supplier', models.CharField(default='GLS', editable=False, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Product GTIN',
            },
        ),
    ]
