# Generated by Django 5.2.7 on 2025-12-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productgtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gtin',
        ),
    ]
