# Generated by Django 5.2.7 on 2025-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_product_gtin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgtin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
