# Generated by Django 5.2.7 on 2025-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productgtin_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
