# Generated by Django 5.2.7 on 2025-12-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_syncqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_min_qty',
            field=models.IntegerField(blank=True, help_text='Minimum quantity for gift price', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sales price when gift promotion applies', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_gift_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='gift_min_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
