# Generated by Django 5.2.7 on 2025-12-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_gift_min_qty_product_gift_sales_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpricehistory',
            old_name='gift_sales_price',
            new_name='aera_gift_sales_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gift_sales_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='productpricehistory',
            name='sales_price',
        ),
        migrations.AddField(
            model_name='product',
            name='aera_gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aera Sales price when gift promotion applies', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='aera_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last calculated Aera sales price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wawibox_gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wawibox Sales price when gift promotion applies', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wawibox_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last calculated Wawibox sales price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='aera_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='wawibox_gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='wawibox_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
