# Generated by Django 5.2.7 on 2025-12-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_gift_sales_price_productpricehistory_aera_gift_sales_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weclapp_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
