# Generated by Django 5.2.7 on 2025-12-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_weclapp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weclapp_article_supply_source_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
