# Generated by Django 5.2.7 on 2026-01-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_weclapp_article_supply_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='gift_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='gift_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
