# Generated by Django 5.2.7 on 2026-01-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_gift_valid_from_product_gift_valid_until_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyncQueue',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
