# Generated by Django 5.2.7 on 2026-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_syncqueue_delete_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_free_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_paid_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='gift_free_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productpricehistory',
            name='gift_paid_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
