# Generated by Django 5.2.7 on 2026-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_product_gift_free_qty_product_gift_paid_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_action_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gift_promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
