# Generated by Django 5.2.7 on 2026-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_product_gift_action_type_product_gift_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='aera_sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Last calculated Aera sales price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='wawibox_sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Last calculated Wawibox sales price', max_digits=12),
        ),
    ]
