# Generated by Django 5.2.7 on 2025-11-14 22:23

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeraOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_token', models.CharField(max_length=100, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_transfer_confirmed', models.DateTimeField(blank=True, null=True)),
                ('date_transfer_released', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('synced_to_weclapp', models.BooleanField(db_index=True, default=False)),
                ('billing_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('billing_vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_postcode', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_email', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_vat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount_full', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount_half', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_rate_full', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vat_rate_half', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('postage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method_id', models.IntegerField(blank=True, null=True)),
                ('order_type_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AeraProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('mpn', models.CharField(blank=True, max_length=25, null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True)),
                ('offer_type_id', models.IntegerField(default=1, editable=False)),
                ('availability_type_id', models.IntegerField(default=1, help_text='1=In stock, 2=Procurement Article')),
                ('different_delivery_time', models.IntegerField(default=0, help_text='Delivery time in days')),
                ('shipped_temperature_stable', models.BooleanField(default=True)),
                ('calculated_sales_price', utils.CleanDecimalField(decimal_places=4, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AERA Data Transfer',
                'verbose_name_plural': 'AERA Data Transfers',
            },
        ),
        migrations.CreateModel(
            name='AeraSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AeraCompetitorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('net_own', models.DecimalField(decimal_places=2, help_text='Net price from AERA for Jasado’s own offer', max_digits=12, verbose_name='AERA Own Net Price')),
                ('net_top_1', models.DecimalField(decimal_places=2, help_text='Lowest competitor net price on AERA', max_digits=12, verbose_name='AERA Top 1 Net Price')),
                ('net_top_2', models.DecimalField(decimal_places=2, help_text='Second lowest competitor net price on AERA', max_digits=12, verbose_name='AERA Top 2 Net Price')),
                ('net_top_3', models.DecimalField(decimal_places=2, help_text='Third lowest competitor net price on AERA', max_digits=12, verbose_name='AERA Top 3 Net Price')),
                ('last_fetch_from_aera', models.DateTimeField(blank=True, help_text='Timestamp of the last data fetch from AERA', null=True, verbose_name='Last Fetched from AERA')),
                ('product', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aera_competitor_price', to='core.product')),
            ],
            options={
                'verbose_name': 'AERA Competitor price',
                'verbose_name_plural': 'AERA Competitor prices',
            },
        ),
        migrations.CreateModel(
            name='AeraOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('order_quantity', models.IntegerField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_value_of_goods', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_type_id', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aera.aeraorder')),
            ],
        ),
    ]
