# Generated by Django 5.2.7 on 2025-11-15 07:28

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeraProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('aera_product_id', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True)),
                ('offer_type_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('discontinuation', models.BooleanField(default=False)),
                ('discontinuation_date', models.DateField(blank=True, null=True)),
                ('availability_type_id', models.IntegerField(blank=True, help_text='1=In stock, 2=Procurement Article', null=True)),
                ('different_delivery_time', models.IntegerField(blank=True, null=True)),
                ('discountable', models.BooleanField(default=False)),
                ('refundable', models.BooleanField(default=False)),
                ('lower_bound_1', models.IntegerField(blank=True, null=True)),
                ('net_price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_bound_2', models.IntegerField(blank=True, null=True)),
                ('net_price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_bound_3', models.IntegerField(blank=True, null=True)),
                ('net_price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_bound_4', models.IntegerField(blank=True, null=True)),
                ('net_price_4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lower_bound_5', models.IntegerField(blank=True, null=True)),
                ('net_price_5', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_offer_valid_through', models.DateField(blank=True, null=True)),
                ('special_offer_discountable', models.BooleanField(default=False)),
                ('special_offer_lower_bound_1', models.IntegerField(blank=True, null=True)),
                ('special_offer_net_price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_offer_lower_bound_2', models.IntegerField(blank=True, null=True)),
                ('special_offer_net_price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_offer_lower_bound_3', models.IntegerField(blank=True, null=True)),
                ('special_offer_net_price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_offer_lower_bound_4', models.IntegerField(blank=True, null=True)),
                ('special_offer_net_price_4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('special_offer_lower_bound_5', models.IntegerField(blank=True, null=True)),
                ('special_offer_net_price_5', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipped_temperature_stable', models.BooleanField(default=False)),
                ('sync_date', models.DateField(blank=True, null=True)),
                ('product', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aera_product', to='core.product')),
            ],
            options={
                'verbose_name': 'Aera Product',
                'verbose_name_plural': 'Aera Products',
            },
        ),
        migrations.CreateModel(
            name='AeraProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('mpn', models.CharField(blank=True, max_length=25, null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True)),
                ('offer_type_id', models.IntegerField(default=1, editable=False)),
                ('availability_type_id', models.IntegerField(default=1, help_text='1=In stock, 2=Procurement Article')),
                ('different_delivery_time', models.IntegerField(default=0, help_text='Delivery time in days')),
                ('shipped_temperature_stable', models.BooleanField(default=True)),
                ('calculated_sales_price', utils.CleanDecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aera Product Update',
                'verbose_name_plural': 'Aera Product Updates',
            },
        ),
        migrations.DeleteModel(
            name='AeraProductData',
        ),
    ]
