# Generated by Django 5.2.7 on 2025-11-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0002_aeraproduct_aeraproductupdate_delete_aeraproductdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeraproduct',
            name='discontinuation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aeraproduct',
            name='special_offer_valid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aeraproduct',
            name='sync_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
