# Generated by Django 5.2.7 on 2025-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0003_alter_aeraproduct_discontinuation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeracompetitorprice',
            name='net_own',
            field=models.DecimalField(decimal_places=2, help_text='Net price from AERA for Jasado’s own offer', max_digits=12, verbose_name='Own Net Price'),
        ),
        migrations.AlterField(
            model_name='aeracompetitorprice',
            name='net_top_1',
            field=models.DecimalField(decimal_places=2, help_text='Lowest competitor net price on AERA', max_digits=12, verbose_name='Top 1 Net Price'),
        ),
        migrations.AlterField(
            model_name='aeracompetitorprice',
            name='net_top_2',
            field=models.DecimalField(decimal_places=2, help_text='Second lowest competitor net price on AERA', max_digits=12, verbose_name='Top 2 Net Price'),
        ),
        migrations.AlterField(
            model_name='aeracompetitorprice',
            name='net_top_3',
            field=models.DecimalField(decimal_places=2, help_text='Third lowest competitor net price on AERA', max_digits=12, verbose_name='Top 3 Net Price'),
        ),
        migrations.AlterField(
            model_name='aeraproduct',
            name='different_delivery_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Delivery time'),
        ),
    ]
