# Generated by Django 5.2.7 on 2025-11-18 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0004_alter_aeracompetitorprice_net_own_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeraproduct',
            name='sync_date',
        ),
        migrations.RemoveField(
            model_name='aeraproductupdate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aeraproduct',
            name='last_fetch_from_aera',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from AERA', verbose_name='Last Fetched from AERA'),
        ),
        migrations.AddField(
            model_name='aeraproductupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aeracompetitorprice',
            name='last_fetch_from_aera',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Timestamp of the last data fetch from AERA', verbose_name='Last Fetched from AERA'),
            preserve_default=False,
        ),
    ]
