# Generated by Django 5.2.7 on 2025-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0005_remove_aeraproduct_sync_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeraExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=25, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('mpn', models.CharField(blank=True, max_length=25, null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True)),
                ('offer_type_id', models.IntegerField(default=1, editable=False)),
                ('availability_type_id', models.IntegerField(default=1, help_text='1=In stock, 2=Procurement Article')),
                ('different_delivery_time', models.IntegerField(default=0, help_text='Delivery time in days', verbose_name='Delivery time')),
                ('shipped_temperature_stable', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_pushed_to_aera', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AeraProductUpdate',
        ),
    ]
