# Generated by Django 5.2.7 on 2025-11-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0006_aeraexport_delete_aeraproductupdate'),
        ('core', '0013_create_default_middleware_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeraproduct',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aera_product', to='core.product'),
        ),
    ]
