# Generated by Django 5.2.7 on 2025-12-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0007_alter_aeraproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeraexport',
            name='gift_min_qty',
            field=models.IntegerField(blank=True, help_text='Minimum quantity for gift price', null=True),
        ),
        migrations.AddField(
            model_name='aeraexport',
            name='gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
