# Generated by Django 5.2.7 on 2026-01-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0009_rename_aera_product_id_aeraproduct_aera_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeraorder',
            name='date_transfer_confirmed',
        ),
        migrations.RemoveField(
            model_name='aeraorder',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='aeraorder',
            name='vat_amount_full',
        ),
        migrations.RemoveField(
            model_name='aeraorder',
            name='vat_amount_half',
        ),
        migrations.RemoveField(
            model_name='aeraorder',
            name='vat_rate_full',
        ),
        migrations.RemoveField(
            model_name='aeraorder',
            name='vat_rate_half',
        ),
        migrations.RemoveField(
            model_name='aeraorderitem',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='aeraorderitem',
            name='total_value_of_goods',
        ),
        migrations.RemoveField(
            model_name='aeraorderitem',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='aeraexport',
            name='gift_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aeraorderitem',
            name='index_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position'),
        ),
    ]
