# Generated by Django 5.2.7 on 2026-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0010_remove_aeraorder_date_transfer_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeraexport',
            name='last_pushed_to_aera',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date pushed to aera'),
        ),
    ]
