# Generated by Django 5.2.7 on 2026-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0011_alter_aeraexport_last_pushed_to_aera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeraorder',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
