# Generated by Django 5.2.7 on 2026-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aera', '0012_alter_aeraorder_fetched_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aeraorder',
            options={'ordering': ['-date_transfer_released']},
        ),
        migrations.AlterField(
            model_name='aeraexport',
            name='gift_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='aeraexport',
            name='sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='aeraexport',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
