# Generated by Django 5.2.7 on 2025-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
