# Generated by Django 5.2.7 on 2025-11-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0002_alter_wawiboxcompetitorprice_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxmasterdata',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
