# Generated by Django 5.2.7 on 2025-11-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0003_alter_wawiboxmasterdata_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='net_own',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='net_top_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='net_top_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='net_top_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
