# Generated by Django 5.2.7 on 2025-11-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wawibox', '0004_alter_wawiboxcompetitorprice_net_own_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WawiboxProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=50, null=True)),
                ('min_order_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_qty_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_qty_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_qty_4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_4', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_order_qty_5', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_5', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wawibox_product', to='core.product')),
            ],
            options={
                'verbose_name': 'Wawibox Product',
                'verbose_name_plural': 'Wawibox Products',
            },
        ),
        migrations.CreateModel(
            name='WawiboxProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_article_no', models.CharField(db_index=True, max_length=50)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('private_label', models.BooleanField(default=False)),
                ('internal_number', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vat_category', models.IntegerField(help_text='0 = Full, 1 = Reduced, 2 = None')),
                ('max_order_quantity', models.IntegerField(blank=True, null=True)),
                ('image1_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image2_url', models.CharField(blank=True, max_length=255, null=True)),
                ('image3_url', models.CharField(blank=True, max_length=255, null=True)),
                ('returnable', models.BooleanField(default=False, help_text='0 = non-returnable, 1 = returnable')),
                ('is_available', models.BooleanField(default=False, help_text='0 = currently out of stock, 1 = currently in stock.')),
                ('delivery_time', models.IntegerField(blank=True, null=True)),
                ('order_number', models.CharField(max_length=100)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('min_order_quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discountable', models.BooleanField(default=False, help_text='0 = not eligible for discount, 1 = eligible for discount.')),
                ('order_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('min_order_quantity_2', models.IntegerField(blank=True, null=True)),
                ('price_2', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discountable_2', models.BooleanField(default=False, help_text='0 = not eligible for discount, 1 = eligible for discount.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wawibox Product Update',
                'verbose_name_plural': 'Wawibox Product Updates',
            },
        ),
        migrations.RemoveField(
            model_name='wawiboxmasterdata',
            name='product',
        ),
        migrations.DeleteModel(
            name='WawiboxProductData',
        ),
        migrations.DeleteModel(
            name='WawiboxMasterData',
        ),
    ]
