# Generated by Django 5.2.7 on 2025-11-15 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_additionalmasterdata_product_and_more'),
        ('wawibox', '0005_wawiboxproduct_wawiboxproductupdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wawibox_competitor_price', to='core.product'),
        ),
    ]
