# Generated by Django 5.2.7 on 2025-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0006_alter_wawiboxcompetitorprice_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wawiboxcompetitorprice',
            name='net_own',
        ),
        migrations.RemoveField(
            model_name='wawiboxcompetitorprice',
            name='vendor_id_own',
        ),
        migrations.RemoveField(
            model_name='wawiboxcompetitorprice',
            name='vendor_name_own',
        ),
        migrations.AddField(
            model_name='wawiboxcompetitorprice',
            name='net_top_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='wawiboxcompetitorprice',
            name='vendor_id_6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wawiboxcompetitorprice',
            name='vendor_name_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='last_fetch_from_wawibox',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
