# Generated by Django 5.2.7 on 2025-11-18 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0007_remove_wawiboxcompetitorprice_net_own_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wawiboxproductupdate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wawiboxproduct',
            name='last_fetch_from_wawibox',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from Wawibox', verbose_name='Last Fetched from Wawibox'),
        ),
        migrations.AddField(
            model_name='wawiboxproductupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wawiboxcompetitorprice',
            name='last_fetch_from_wawibox',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Timestamp of the last data fetch from Wawibox', verbose_name='Last Fetched from Wawibox'),
            preserve_default=False,
        ),
    ]
