# Generated by Django 5.2.7 on 2025-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0008_remove_wawiboxproductupdate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WawiboxExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_article_no', models.CharField(db_index=True, max_length=50)),
                ('manufacturer_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('private_label', models.BooleanField(default=False, editable=False)),
                ('internal_number', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, editable=False, null=True)),
                ('vat_category', models.IntegerField(blank=True, editable=False, help_text='0 = Full, 1 = Reduced, 2 = None', null=True)),
                ('max_order_quantity', models.IntegerField(blank=True, editable=False, null=True)),
                ('image1_url', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image2_url', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('image3_url', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('returnable', models.BooleanField(default=False, editable=False, help_text='0 = non-returnable, 1 = returnable')),
                ('is_available', models.BooleanField(default=False, editable=False, help_text='0 = currently out of stock, 1 = currently in stock.')),
                ('delivery_time', models.IntegerField(blank=True, editable=False, null=True)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('valid_from', models.DateField(blank=True, editable=False, null=True)),
                ('valid_until', models.DateField(blank=True, editable=False, null=True)),
                ('min_order_quantity', models.IntegerField(blank=True, editable=False, null=True)),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('discountable', models.BooleanField(default=False, editable=False, help_text='0 = not eligible for discount, 1 = eligible for discount.')),
                ('order_number_2', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('min_order_quantity_2', models.IntegerField(blank=True, editable=False, null=True)),
                ('price_2', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=14, null=True)),
                ('discountable_2', models.BooleanField(default=False, editable=False, help_text='0 = not eligible for discount, 1 = eligible for discount.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_pushed_to_wawibox', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WawiboxProductUpdate',
        ),
    ]
