# Generated by Django 5.2.7 on 2025-11-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0009_wawiboxexport_delete_wawiboxproductupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxexport',
            name='manufacturer_article_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
