# Generated by Django 5.2.7 on 2025-12-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0010_alter_wawiboxexport_manufacturer_article_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxexport',
            name='min_order_quantity_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
