# Generated by Django 5.2.7 on 2026-01-17 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_gift_valid_from_product_gift_valid_until_and_more'),
        ('wawibox', '0011_alter_wawiboxexport_min_order_quantity_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxexport',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxproduct',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wawibox_product', to='core.product'),
        ),
    ]
