# Generated by Django 5.2.7 on 2026-01-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wawibox', '0012_alter_wawiboxexport_valid_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wawiboxexport',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='discountable',
            field=models.BooleanField(default=False, help_text='0 = not eligible for discount, 1 = eligible for discount.'),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='discountable_2',
            field=models.BooleanField(default=False, help_text='0 = not eligible for discount, 1 = eligible for discount.'),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='is_available',
            field=models.BooleanField(default=False, help_text='0 = currently out of stock, 1 = currently in stock.'),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='min_order_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='order_number_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='returnable',
            field=models.BooleanField(default=False, help_text='0 = non-returnable, 1 = returnable'),
        ),
        migrations.AlterField(
            model_name='wawiboxexport',
            name='vat_category',
            field=models.IntegerField(blank=True, help_text='0 = Full, 1 = Reduced, 2 = None', null=True),
        ),
    ]
