# Generated by Django 5.2.7 on 2026-01-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_product_weclapp_article_supply_source_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField()),
                ('expires_in', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopwareExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopware_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sales_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('gift_sales_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('gift_min_qty', models.IntegerField(blank=True, help_text='Minimum quantity for gift price', null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('mpn', models.CharField(blank=True, max_length=25, null=True)),
                ('gtin', models.CharField(blank=True, max_length=14, null=True)),
                ('shipped_temperature_stable', models.BooleanField(default=True)),
                ('length', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('stock', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_pushed_to_shopware', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopwareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopware_id', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopware_product', to='core.product')),
            ],
            options={
                'verbose_name': 'Shopware Product',
                'verbose_name_plural': 'Shopware Products',
            },
        ),
    ]
