# Generated by Django 5.2.7 on 2026-01-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopwareexport',
            name='gift_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
