# Generated by Django 5.2.7 on 2026-01-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopware', '0002_shopwareexport_gift_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopwareexport',
            name='gift_free_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopwareexport',
            name='gift_paid_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopwareexport',
            name='gift_valid_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
