# Generated by Django 5.2.7 on 2026-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalheld', '0002_alter_dentalheldorderitem_packing_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalheldorder',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalheldorderitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
