# Generated by Django 5.2.7 on 2026-01-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalheld', '0003_alter_dentalheldorder_fetched_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalheldproduct',
            name='article_id',
        ),
        migrations.AddField(
            model_name='dentalheldproduct',
            name='sku',
            field=models.CharField(default=22, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
