# Generated by Django 5.2.7 on 2026-01-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalheld', '0004_remove_dentalheldproduct_article_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentalheldorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dentalheldexport',
            name='last_pushed_to_dentalheld',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
