# Generated by Django 5.2.7 on 2025-11-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_additionalmasterdata_product_and_more'),
        ('gls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsmasterdata',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_master_data', to='core.product', verbose_name='Product SKU'),
        ),
        migrations.AlterField(
            model_name='glspricelist',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_price_list', to='core.product'),
        ),
        migrations.AlterField(
            model_name='glspromotionposition',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_promotional_position', to='core.product'),
        ),
        migrations.AlterField(
            model_name='glspromotionprice',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_promotional_price', to='core.product'),
        ),
    ]
