# Generated by Django 5.2.7 on 2025-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0002_alter_glsmasterdata_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsmasterdata',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer no'),
        ),
        migrations.AlterField(
            model_name='glsmasterdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last synced'),
        ),
        migrations.AlterField(
            model_name='glsorderconfirmation',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, editable=False),
        ),
    ]
