# Generated by Django 5.2.7 on 2025-11-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0003_alter_glsmasterdata_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glsbackorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glsmasterdata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='glsorderconfirmation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glspricelist',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='glspromotionheader',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glspromotionposition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glspromotionprice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='glsstocklevel',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='glsbackorder',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glsmasterdata',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glsorderconfirmation',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glsorderstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='glspricelist',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glspromotionheader',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glspromotionposition',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glspromotionprice',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glsstocklevel',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
        migrations.AddField(
            model_name='glssupplier',
            name='last_fetch_from_gls',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last data fetch from GLS', verbose_name='Last Fetched from GLS'),
        ),
    ]
