# Generated by Django 5.2.7 on 2025-11-26 05:16

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0004_remove_glsbackorder_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLSHandlingSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_group_no', models.CharField(max_length=10, unique=True)),
                ('article_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_type', models.CharField(choices=[('percent', 'Percent'), ('absolute', 'Absolute')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'GLS Handling Surcharge',
            },
        ),
        migrations.CreateModel(
            name='GLSProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_group_no', models.CharField(max_length=20, unique=True)),
                ('product_group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='glspricelist',
            name='bill_back_price',
            field=utils.CleanDecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='glspricelist',
            name='purchase_price',
            field=utils.CleanDecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='glspricelist',
            name='recommended_retail_price',
            field=utils.CleanDecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
