# Generated by Django 5.2.7 on 2025-11-26 05:33

from django.db import migrations
from decimal import Decimal
from apps.gls.models import GLSHandlingSurcharge


def add_gls_handling_surcharges(apps, schema_editor):

    data = [
        ("0", "Material & Instrumente", Decimal("8.00")),
        ("1", "Kleingeräte", Decimal("4.00")),
        ("11", "Arzneimittel", Decimal("10.00")),
        ("2", "Ersatzteile", Decimal("8.00")),
        ("3", "Zähne", Decimal("13.00")),
        ("30", "Eigenmarke PROCLINIC", Decimal("12.00")),
        ("31", "Eigenmarke PROCLINIC Expert", Decimal("12.00")),
        ("32", "Eigenmarke PROCLINIC Bestdent", Decimal("12.00")),
        ("33", "Eigenmarke DC DentalCentral", Decimal("12.00")),
        ("5", "Hand- u. Winkelstücke / Turbinen", Decimal("5.00")),
        ("8", "Büromaterial / Betriebsmittel", Decimal("8.00")),
    ]

    for no, name, value in data:
        GLSHandlingSurcharge.objects.update_or_create(
            article_group_no=no,
            defaults={
                "article_group_name": name,
                "value": value,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("gls", "0005_glshandlingsurcharge_glsproductgroup_and_more"),
    ]

    operations = [
        migrations.RunPython(add_gls_handling_surcharges, migrations.RunPython.noop),
    ]
