# Generated by Django 5.2.7 on 2025-12-06 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productgtin'),
        ('gls', '0006_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsmasterdata',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gls_master_data', to='core.product', verbose_name='Product SKU'),
        ),
    ]
