# Generated by Django 5.2.7 on 2025-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0007_alter_glsmasterdata_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsorderstatus',
            name='admin_notified',
            field=models.BooleanField(default=False),
        ),
    ]
