# Generated by Django 5.2.7 on 2025-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0008_alter_glsorderstatus_admin_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='glsmasterdata',
            name='row_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glspricelist',
            name='row_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glsstocklevel',
            name='row_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='glssupplier',
            name='row_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
