# Generated by Django 5.2.7 on 2025-12-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0009_glsmasterdata_row_hash_glspricelist_row_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glspromotionheader',
            name='row_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
