# Generated by Django 5.2.7 on 2025-12-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0010_glspromotionheader_row_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='glssupplier',
            name='weclapp_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
