# Generated by Django 5.2.7 on 2025-12-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0011_glssupplier_weclapp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='glsproductgroup',
            name='weclapp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
