# Generated by Django 5.2.7 on 2026-01-13 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0012_glsproductgroup_weclapp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glsorderstatus',
            name='last_sent_qty',
        ),
        migrations.AddField(
            model_name='glsorderstatus',
            name='last_sent_hash',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='carrier_code',
            field=models.CharField(blank=True, default='20', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='currency',
            field=models.CharField(blank=True, default='EUR', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='distribution_key',
            field=models.CharField(blank=True, default='07', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='document_type',
            field=models.CharField(blank=True, default='LS', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='order_type',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='record_type',
            field=models.CharField(default='K', max_length=5),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='redelivery_method',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='glsorderline',
            name='record_type',
            field=models.CharField(default='Z', max_length=5),
        ),
        migrations.AlterField(
            model_name='glsorderstatus',
            name='article_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='sku'),
        ),
        migrations.AlterUniqueTogether(
            name='glsorderline',
            unique_together={('order_number', 'position')},
        ),
    ]
