# Generated by Django 5.2.7 on 2026-01-20 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0013_remove_glsorderstatus_last_sent_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsorderheader',
            name='header_renamed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='header_uploaded',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Sent to GLS'),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='lines_renamed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='glsorderheader',
            name='lines_uploaded',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='glsorderline',
            name='order_header',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gls.glsorderheader'),
        ),
    ]
