# Generated by Django 5.2.7 on 2026-01-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0014_alter_glsorderheader_header_renamed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glsorderstatus',
            name='synced_to_weclapp',
            field=models.BooleanField(default=False),
        ),
    ]
