# Generated by Django 5.2.7 on 2026-01-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0015_glsorderstatus_synced_to_weclapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsorderstatus',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Fully Delivered'),
        ),
    ]
