# Generated by Django 5.2.7 on 2026-01-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gls', '0016_alter_glsorderstatus_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glsmasterdata',
            name='customs_position',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
