# Generated by Django 5.2.7 on 2025-12-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weclapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Master Data Transfer', max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_completed', models.DateTimeField(blank=True, null=True)),
                ('task_duration', models.CharField(default='Not Completed yet', max_length=100)),
            ],
        ),
    ]
